// Generated by CoffeeScript 1.4.0
(function() {
  var Leaderboard, redis;

  redis = require('redis');

  Leaderboard = (function() {
    var DEFAULT_OPTIONS, DEFAULT_REDIS_OPTIONS;

    Leaderboard.DEFAULT_PAGE_SIZE = 25;

    DEFAULT_OPTIONS = {
      'pageSize': Leaderboard.DEFAULT_PAGE_SIZE,
      'reverse': false
    };

    Leaderboard.DEFAULT_REDIS_HOST = 'localhost';

    Leaderboard.DEFAULT_REDIS_PORT = 6379;

    DEFAULT_REDIS_OPTIONS = {
      'host': Leaderboard.DEFAULT_REDIS_HOST,
      'port': Leaderboard.DEFAULT_REDIS_PORT
    };

    function Leaderboard(leaderboardName, options, redisOptions) {
      this.leaderboardName = leaderboardName;
      if (options == null) {
        options = DEFAULT_OPTIONS;
      }
      if (redisOptions == null) {
        redisOptions = DEFAULT_REDIS_OPTIONS;
      }
      this.reverse = options['reverse'];
      this.pageSize = options['pageSize'];
      if (this.pageSize === null || this.pageSize < 1) {
        this.pageSize = Leaderboard.DEFAULT_PAGE_SIZE;
      }
      this.redisConnection = redisOptions['redis_connection'];
      if (this.redisConnection != null) {
        delete redisOptions['redis_connection'];
      }
      if (this.redisConnection == null) {
        this.redisConnection = redis.createClient(redisOptions['port'], redisOptions['host']);
      }
    }

    Leaderboard.prototype.disconnect = function() {
      return this.redisConnection.quit(function(err, reply) {});
    };

    Leaderboard.prototype.deleteLeaderboard = function(callback) {
      return this.deleteLeaderboardNamed(this.leaderboardName, callback);
    };

    Leaderboard.prototype.deleteLeaderboardNamed = function(leaderboardName, callback) {
      var transaction;
      transaction = this.redisConnection.multi();
      transaction.del(leaderboardName);
      transaction.del(this.memberDataKey(leaderboardName));
      return transaction.exec(function(err, reply) {
        if (callback) {
          return callback(reply);
        }
      });
    };

    Leaderboard.prototype.rankMember = function(member, score, memberData, callback) {
      if (memberData == null) {
        memberData = null;
      }
      return this.rankMemberIn(this.leaderboardName, member, score, memberData, callback);
    };

    Leaderboard.prototype.rankMemberIn = function(leaderboardName, member, score, memberData, callback) {
      var transaction;
      if (memberData == null) {
        memberData = null;
      }
      transaction = this.redisConnection.multi();
      transaction.zadd(leaderboardName, score, member);
      if (memberData != null) {
        transaction.hset(this.memberDataKey(leaderboardName), member, memberData);
      }
      return transaction.exec(function(err, reply) {
        if (callback) {
          return callback(reply);
        }
      });
    };

    Leaderboard.prototype.rankMemberIf = function(rankConditional, member, score, memberData, callback) {
      if (memberData == null) {
        memberData = null;
      }
      return this.rankMemberIfIn(this.leaderboardName, rankConditional, member, score, memberData, callback);
    };

    Leaderboard.prototype.rankMemberIfIn = function(leaderboardName, rankConditional, member, score, currentScore, memberData, callback) {
      if (memberData == null) {
        memberData = null;
      }
      if (rankConditional(member, currentScore, score, memberData, {
        'reverse': this.reverse
      })) {
        return this.rankMemberIn(leaderboardName, member, score, memberData, callback);
      }
    };

    Leaderboard.prototype.rankMembers = function(membersAndScores, callback) {
      return this.rankMembersIn(this.leaderboardName, membersAndScores, callback);
    };

    Leaderboard.prototype.rankMembersIn = function(leaderboardName, membersAndScores, callback) {
      var index, slice, transaction, _i, _ref;
      transaction = this.redisConnection.multi();
      for (index = _i = 0, _ref = membersAndScores.length; _i < _ref; index = _i += 2) {
        slice = membersAndScores.slice(index, index + 2);
        transaction.zadd(leaderboardName, slice[1], slice[0]);
      }
      return transaction.exec(function(err, reply) {
        if (callback) {
          return callback(reply);
        }
      });
    };

    Leaderboard.prototype.memberDataFor = function(member, callback) {
      return this.memberDataForIn(this.leaderboardName, member, callback);
    };

    Leaderboard.prototype.memberDataForIn = function(leaderboardName, member, callback) {
      if (callback == null) {
        callback = function() {};
      }
      return this.redisConnection.hget(this.memberDataKey(leaderboardName), member, function(err, reply) {
        return callback(reply);
      });
    };

    Leaderboard.prototype.updateMemberData = function(member, memberData, callback) {
      return this.updateMemberDataFor(this.leaderboardName, member, memberData, callback);
    };

    Leaderboard.prototype.updateMemberDataFor = function(leaderboardName, member, memberData, callback) {
      return this.redisConnection.hset(this.memberDataKey(leaderboardName), member, memberData, function(err, reply) {
        if (callback) {
          return callback(reply);
        }
      });
    };

    Leaderboard.prototype.removeMemberData = function(member, callback) {
      return this.remberMemberDataFor(this.leaderboardName, member, callback);
    };

    Leaderboard.prototype.remberMemberDataFor = function(leaderboardName, member, callback) {
      return this.redisConnection.hdel(this.memberDataKey(leaderboardName), member, function(err, reply) {
        if (callback) {
          return callback(reply);
        }
      });
    };

    Leaderboard.prototype.removeMember = function(member, callback) {
      return this.removeMemberFrom(this.leaderboardName, member, callback);
    };

    Leaderboard.prototype.removeMemberFrom = function(leaderboardName, member, callback) {
      var transaction;
      transaction = this.redisConnection.multi();
      transaction.zrem(leaderboardName, member);
      transaction.hdel(this.memberDataKey(leaderboardName), member);
      return transaction.exec(function(err, reply) {
        if (callback) {
          return callback(reply);
        }
      });
    };

    Leaderboard.prototype.totalMembers = function(callback) {
      return this.totalMembersIn(this.leaderboardName, callback);
    };

    Leaderboard.prototype.totalMembersIn = function(leaderboardName, callback) {
      return this.redisConnection.zcard(leaderboardName, function(err, reply) {
        return callback(reply);
      });
    };

    Leaderboard.prototype.totalPages = function(pageSize, callback) {
      if (pageSize == null) {
        pageSize = null;
      }
      return this.totalPagesIn(this.leaderboardName, pageSize, callback);
    };

    Leaderboard.prototype.totalPagesIn = function(leaderboardName, pageSize, callback) {
      if (pageSize == null) {
        pageSize = null;
      }
      if (pageSize == null) {
        pageSize = this.pageSize;
      }
      return this.redisConnection.zcard(leaderboardName, function(err, reply) {
        return callback(Math.ceil(reply / pageSize));
      });
    };

    Leaderboard.prototype.totalMembersInScoreRange = function(minScore, maxScore, callback) {
      return this.totalMembersInScoreRangeIn(this.leaderboardName, minScore, maxScore, callback);
    };

    Leaderboard.prototype.totalMembersInScoreRangeIn = function(leaderboardName, minScore, maxScore, callback) {
      return this.redisConnection.zcount(leaderboardName, minScore, maxScore, function(err, reply) {
        return callback(reply);
      });
    };

    Leaderboard.prototype.changeScoreFor = function(member, delta, callback) {
      return this.changeScoreForMemberIn(this.leaderboardName, member, delta, callback);
    };

    Leaderboard.prototype.changeScoreForMemberIn = function(leaderboardName, member, delta, callback) {
      return this.redisConnection.zincrby(leaderboardName, delta, member, function(err, reply) {
        if (callback) {
          return callback(reply);
        }
      });
    };

    Leaderboard.prototype.rankFor = function(member, callback) {
      return this.rankForIn(this.leaderboardName, member, callback);
    };

    Leaderboard.prototype.rankForIn = function(leaderboardName, member, callback) {
      if (this.reverse) {
        return this.redisConnection.zrank(leaderboardName, member, function(err, reply) {
          if (reply) {
            return callback(reply + 1);
          }
        });
      } else {
        return this.redisConnection.zrevrank(leaderboardName, member, function(err, reply) {
          if (reply) {
            return callback(reply + 1);
          }
        });
      }
    };

    Leaderboard.prototype.scoreFor = function(member, callback) {
      return this.scoreForIn(this.leaderboardName, member, callback);
    };

    Leaderboard.prototype.scoreForIn = function(leaderboardName, member, callback) {
      return this.redisConnection.zscore(leaderboardName, member, function(err, reply) {
        if (reply != null) {
          return callback(parseFloat(reply));
        } else {
          return callback(null);
        }
      });
    };

    Leaderboard.prototype.checkMember = function(member, callback) {
      return this.checkMemberIn(this.leaderboardName, member, callback);
    };

    Leaderboard.prototype.checkMemberIn = function(leaderboardName, member, callback) {
      return this.redisConnection.zscore(leaderboardName, member, function(err, reply) {
        return callback(reply != null);
      });
    };

    Leaderboard.prototype.scoreAndRankFor = function(member, callback) {
      return this.scoreAndRankForIn(this.leaderboardName, member, callback);
    };

    Leaderboard.prototype.scoreAndRankForIn = function(leaderboardName, member, callback) {
      var transaction;
      transaction = this.redisConnection.multi();
      transaction.zscore(leaderboardName, member);
      if (this.reverse) {
        transaction.zrank(leaderboardName, member);
      } else {
        transaction.zrevrank(leaderboardName, member);
      }
      return transaction.exec(function(err, replies) {
        var scoreAndRankData;
        if (replies) {
          scoreAndRankData = {};
          if (replies[0] != null) {
            scoreAndRankData['score'] = parseFloat(replies[0]);
          } else {
            scoreAndRankData['score'] = null;
          }
          if (replies[1] != null) {
            scoreAndRankData['rank'] = replies[1] + 1;
          } else {
            scoreAndRankData['rank'] = null;
          }
          scoreAndRankData['member'] = member;
          return callback(scoreAndRankData);
        }
      });
    };

    Leaderboard.prototype.removeMembersInScoreRange = function(minScore, maxScore, callback) {
      return this.removeMembersInScoreRangeIn(this.leaderboardName, minScore, maxScore);
    };

    Leaderboard.prototype.removeMembersInScoreRangeIn = function(leaderboardName, minScore, maxScore, callback) {
      return this.redisConnection.zremrangebyscore(leaderboardName, minScore, maxScore, function(err, reply) {
        if (callback) {
          return callback(reply);
        }
      });
    };

    Leaderboard.prototype.percentileFor = function(member, callback) {
      return this.percentileForIn(this.leaderboardName, member, callback);
    };

    Leaderboard.prototype.percentileForIn = function(leaderboardName, member, callback) {
      var _this = this;
      return this.checkMemberIn(leaderboardName, member, function(reply) {
        var transaction;
        if (reply) {
          transaction = _this.redisConnection.multi();
          transaction.zcard(leaderboardName);
          transaction.zrevrank(leaderboardName, member);
          return transaction.exec(function(err, replies) {
            var percentile;
            if (replies) {
              percentile = Math.ceil(parseFloat((parseFloat(replies[0] - replies[1] - 1)) / parseFloat(replies[0]) * 100));
              if (this.reverse) {
                return callback(100 - percentile);
              } else {
                return callback(percentile);
              }
            }
          });
        }
      });
    };

    Leaderboard.prototype.pageFor = function(member, pageSize, callback) {
      if (pageSize == null) {
        pageSize = this.DEFAULT_PAGE_SIZE;
      }
      return this.pageForIn(this.leaderboardName, member, pageSize, callback);
    };

    Leaderboard.prototype.pageForIn = function(leaderboardName, member, pageSize, callback) {
      var transaction;
      if (pageSize == null) {
        pageSize = this.DEFAULT_PAGE_SIZE;
      }
      transaction = this.redisConnection.multi();
      if (this.reverse) {
        transaction.zrank(leaderboardName, member);
      } else {
        transaction.zrevrank(leaderboardName, member);
      }
      return transaction.exec(function(err, replies) {
        var rankForMember;
        rankForMember = replies[0];
        if (rankForMember != null) {
          rankForMember += 1;
        } else {
          rankForMember = 0;
        }
        return callback(Math.ceil(rankForMember / pageSize));
      });
    };

    Leaderboard.prototype.expireLeaderboard = function(seconds, callback) {
      return this.expireLeaderboardFor(this.leaderboardName, seconds, callback);
    };

    Leaderboard.prototype.expireLeaderboardFor = function(leaderboardName, seconds, callback) {
      return this.redisConnection.expire(leaderboardName, seconds, function(err, reply) {
        if (callback) {
          return callback(reply);
        }
      });
    };

    Leaderboard.prototype.expireLeaderboardAt = function(timestamp, callback) {
      return this.expireLeaderboardAtFor(this.leaderboardName, timestamp, callback);
    };

    Leaderboard.prototype.expireLeaderboardAtFor = function(leaderboardName, timestamp, callback) {
      return this.redisConnection.expireat(leaderboardName, timestamp, function(err, reply) {
        if (callback) {
          return callback(reply);
        }
      });
    };

    Leaderboard.prototype.rankedInList = function(members, options, callback) {
      if (options == null) {
        options = {};
      }
      return this.rankedInListIn(this.leaderboardName, members, options, callback);
    };

    Leaderboard.prototype.rankedInListIn = function(leaderboardName, members, options, callback) {
      var member, ranksForMembers, transaction, _i, _len,
        _this = this;
      if (options == null) {
        options = {};
      }
      ranksForMembers = [];
      transaction = this.redisConnection.multi();
      for (_i = 0, _len = members.length; _i < _len; _i++) {
        member = members[_i];
        if (this.reverse) {
          transaction.zrank(this.leaderboardName, member);
        } else {
          transaction.zrevrank(this.leaderboardName, member);
        }
        transaction.zscore(this.leaderboardName, member);
      }
      return transaction.exec(function(err, replies) {
        var index, _j, _len1, _results;
        _results = [];
        for (index = _j = 0, _len1 = members.length; _j < _len1; index = ++_j) {
          member = members[index];
          _results.push((function(member) {
            var data;
            data = {};
            data['member'] = member;
            data['rank'] = replies[index * 2] + 1;
            if (replies[index * 2 + 1]) {
              data['score'] = parseFloat(replies[index * 2 + 1]);
            } else {
              data['score'] = null;
              data['rank'] = null;
            }
            if (options['with_member_data']) {
              return _this.memberDataForIn(_this.leaderboardName, member, function(memberdata) {
                data['member_data'] = memberdata;
                ranksForMembers.push(data);
                if (ranksForMembers.length === members.length) {
                  switch (options['sort_by']) {
                    case 'rank':
                      ranksForMembers.sort(function(a, b) {
                        return a.rank > b.rank;
                      });
                      break;
                    case 'score':
                      ranksForMembers.sort(function(a, b) {
                        return a.score > b.score;
                      });
                  }
                  return callback(ranksForMembers);
                }
              });
            } else {
              ranksForMembers.push(data);
              if (ranksForMembers.length === members.length) {
                switch (options['sort_by']) {
                  case 'rank':
                    ranksForMembers.sort(function(a, b) {
                      return a.rank > b.rank;
                    });
                    break;
                  case 'score':
                    ranksForMembers.sort(function(a, b) {
                      return a.score > b.score;
                    });
                }
                return callback(ranksForMembers);
              }
            }
          })(member));
        }
        return _results;
      });
    };

    Leaderboard.prototype.leaders = function(currentPage, options, callback) {
      if (options == null) {
        options = {};
      }
      return this.leadersIn(this.leaderboardName, currentPage, options, callback);
    };

    Leaderboard.prototype.leadersIn = function(leaderboardName, currentPage, options, callback) {
      var pageSize,
        _this = this;
      if (options == null) {
        options = {};
      }
      if (currentPage < 1) {
        currentPage = 1;
      }
      pageSize = options['page_size'] || this.pageSize;
      return this.totalPages(pageSize, function(totalPages) {
        var endingOffset, indexForRedis, startingOffset;
        if (currentPage > totalPages) {
          currentPage = totalPages;
        }
        indexForRedis = currentPage - 1;
        startingOffset = indexForRedis * pageSize;
        endingOffset = (startingOffset + pageSize) - 1;
        if (_this.reverse) {
          return _this.redisConnection.zrange(leaderboardName, startingOffset, endingOffset, function(err, reply) {
            return _this.rankedInListIn(leaderboardName, reply, options, callback);
          });
        } else {
          return _this.redisConnection.zrevrange(leaderboardName, startingOffset, endingOffset, function(err, reply) {
            return _this.rankedInListIn(leaderboardName, reply, options, callback);
          });
        }
      });
    };

    Leaderboard.prototype.allLeaders = function(options, callback) {
      if (options == null) {
        options = {};
      }
      return this.allLeadersFrom(this.leaderboardName, options, callback);
    };

    Leaderboard.prototype.allLeadersFrom = function(leaderboardName, options, callback) {
      var _this = this;
      if (options == null) {
        options = {};
      }
      if (this.reverse) {
        return this.redisConnection.zrange(leaderboardName, 0, -1, function(err, reply) {
          return _this.rankedInListIn(leaderboardName, reply, options, callback);
        });
      } else {
        return this.redisConnection.zrevrange(leaderboardName, 0, -1, function(err, reply) {
          return _this.rankedInListIn(leaderboardName, reply, options, callback);
        });
      }
    };

    Leaderboard.prototype.membersFromScoreRange = function(minimumScore, maximumScore, options, callback) {
      if (options == null) {
        options = {};
      }
      return this.membersFromScoreRangeIn(this.leaderboardName, minimumScore, maximumScore, options, callback);
    };

    Leaderboard.prototype.membersFromScoreRangeIn = function(leaderboardName, minimumScore, maximumScore, options, callback) {
      var _this = this;
      if (options == null) {
        options = {};
      }
      if (this.reverse) {
        return this.redisConnection.zrangebyscore(leaderboardName, minimumScore, maximumScore, function(err, reply) {
          return _this.rankedInListIn(leaderboardName, reply, options, callback);
        });
      } else {
        return this.redisConnection.zrevrangebyscore(leaderboardName, maximumScore, minimumScore, function(err, reply) {
          return _this.rankedInListIn(leaderboardName, reply, options, callback);
        });
      }
    };

    Leaderboard.prototype.membersFromRankRange = function(startingRank, endingRank, options, callback) {
      if (options == null) {
        options = {};
      }
      return this.membersFromRankRangeIn(this.leaderboardName, startingRank, endingRank, options, callback);
    };

    Leaderboard.prototype.membersFromRankRangeIn = function(leaderboardName, startingRank, endingRank, options, callback) {
      var _this = this;
      startingRank -= 1;
      if (startingRank < 0) {
        startingRank = 0;
      }
      endingRank -= 1;
      if (endingRank < 0) {
        endingRank = 0;
      }
      if (this.reverse) {
        return this.redisConnection.zrange(leaderboardName, startingRank, endingRank, function(err, reply) {
          return _this.rankedInListIn(leaderboardName, reply, options, callback);
        });
      } else {
        return this.redisConnection.zrevrange(leaderboardName, startingRank, endingRank, function(err, reply) {
          return _this.rankedInListIn(leaderboardName, reply, options, callback);
        });
      }
    };

    Leaderboard.prototype.memberAt = function(position, options, callback) {
      if (options == null) {
        options = {};
      }
      return this.memberAtIn(this.leaderboardName, position, options, callback);
    };

    Leaderboard.prototype.memberAtIn = function(leaderboardName, position, options, callback) {
      if (options == null) {
        options = {};
      }
      return this.membersFromRankRangeIn(leaderboardName, position, position, options, callback);
    };

    Leaderboard.prototype.aroundMe = function(member, options, callback) {
      if (options == null) {
        options = {};
      }
      return this.aroundMeIn(this.leaderboardName, member, options, callback);
    };

    Leaderboard.prototype.aroundMeIn = function(leaderboardName, member, options, callback) {
      var _this = this;
      if (options == null) {
        options = {};
      }
      if (this.reverse) {
        return this.redisConnection.zrank(leaderboardName, member, function(err, reply) {
          var endingOffset, startingOffset;
          if (reply != null) {
            startingOffset = parseInt(Math.ceil(reply - (_this.pageSize / 2)));
            if (startingOffset < 0) {
              startingOffset = 0;
            }
            endingOffset = (startingOffset + _this.pageSize) - 1;
            return _this.redisConnection.zrange(leaderboardName, startingOffset, endingOffset, function(err, reply) {
              return _this.rankedInListIn(leaderboardName, reply, options, callback);
            });
          } else {
            return [];
          }
        });
      } else {
        return this.redisConnection.zrevrank(leaderboardName, member, function(err, reply) {
          var endingOffset, startingOffset;
          if (reply != null) {
            startingOffset = parseInt(Math.ceil(reply - (_this.pageSize / 2)));
            if (startingOffset < 0) {
              startingOffset = 0;
            }
            endingOffset = (startingOffset + _this.pageSize) - 1;
            return _this.redisConnection.zrevrange(leaderboardName, startingOffset, endingOffset, function(err, reply) {
              return _this.rankedInListIn(leaderboardName, reply, options, callback);
            });
          } else {
            return [];
          }
        });
      }
    };

    Leaderboard.prototype.memberDataKey = function(leaderboardName) {
      return "" + leaderboardName + ":member_data";
    };

    return Leaderboard;

  })();

  module.exports = Leaderboard;

}).call(this);
